version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg_mqtt
    restart: unless-stopped
    environment:
      POSTGRES_DB: mqttdb
      POSTGRES_USER: mqttuser
      POSTGRES_PASSWORD: mqttpass
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mqtt_network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

  api-predictions:
    build:
      context: ./api-predictions
    container_name: mqtt_microservice
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./shared:/app/shared
    depends_on:
      - postgres
    networks:
      - mqtt_network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

  api-models:
    build:
      context: ./api-model
    container_name: model_api
    restart: unless-stopped
    ports:
      - "3006:8000"
    volumes:
      - ./shared:/app/data:ro # Keep this for now, but be aware
    networks:
      - mqtt_network

volumes:
  pg_data:

networks:
  mqtt_network:
    driver: bridge