version: '3.8'

services:
  node_api:
    build:
      context: ./predictions-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MQTT_BROKER=mqtt://test.mosquitto.org
      - MQTT_PORT=1883
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=admin
      - PG_PASSWORD=admin123
      - PG_DATABASE=prediccionesdb
      - MODEL_API_URL=http://model_api:8000/predict
    depends_on:
      - db
      - model_api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: '0.5'
    networks:
      - app_network

  model_api:
    build:
      context: ./model-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 350M
          cpus: '0.6'
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: predicciones_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: prediccionesdb
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.4'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: